#!/usr/bin/env python
godot_cpp_path = "../../addons/gdext_wizard/godot-cpp-master"

env = SConscript(godot_cpp_path + "/SConstruct")

env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp")

library = env.SharedLibrary(
	target="../../bin/libcore{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
	source=sources,
)

Default(library)
